### ISSUE TITLE
Grub menu timeout of 30 seconds

### ISSUE THREAD

**Issue by o-alquimista** [elementary/triage#109]
### What Happened?

The grub menu appears on every boot, for 30 seconds.

There are similar (but closed) issues here:

- https://github.com/elementary/os-patches/issues/178

### Steps to Reproduce

1. Install elementary
2. Boot the installed system

### Expected Behavior

Set timeout to a lower number, or hide the Grub menu like Ubuntu does.

### OS Version

6.1 (Jólnir)

### Software Version

Latest release (I have run all updates)

### Hardware Info

- Dell Inspiron 15 3583 with 8th-gen Intel CPU and graphics
- Secure boot on, UEFI mode, legacy support disabled

**Comment by o-alquimista** [comment]
Can no longer reproduce on elementary 7

**Comment by o-alquimista** [comment]
Can reproduce again on elementary 7.1. Fresh install.

**Comment by IanHead** [comment]
Ditto here. Setting `GRUB_RECORDFAIL_TIMEOUT=0` in `/etc/default/grub` and running `sudo grub-update` works around the problem.

**Comment by o-alquimista** [comment]
@lenemter what's incomplete?

**Comment by lenemter** [comment]
@o-alquimista I think 30 seconds timeout is default grub behavior and there are instructions to reduce the timeout on the Internet. I'll remove the Incomplete tag, but this topic needs discussion.

**Comment by o-alquimista** [comment]
It was discussed, and it was supposed to be fixed in https://github.com/elementary/os-patches/issues/178, but it's back in Horus (7) and newer.

Most people expect the Ubuntu behavior by default (no timeout, hidden menu, except if SHIFT is pressed or if boot fails).

**Comment by lenemter** [comment]
I remember this issue being fixed, but I can reproduce it on OS 7 daily.

**Comment by danirabbit** [comment]
It looks like the default is set to 10 seconds and [we carry a patch to make that 5 seconds](https://github.com/elementary/os-patches/commit/29b8efe22c8fef47b8bdf961e9734863b58cc945), so I'm not sure what's going on here.

This would also be fixed by switching to Systemd boot :sweat_smile:

**Comment by invarianz** [comment]
I'm facing the same issue on Elementary OS 7.1 Horus. The GRUB Timeout Settings do not get reflected in the grub config. I still get 30s of timeout regardless of any changes in `/etc/default/grub` followed by `sudo update-grub`.

However, I also changed a kernel parameter via `GRUB_CMDLINE_LINUX_DEFAULT` and checked after `sudo update-grub` and a reboot, in the file `/proc/cmdline` if it was correctly set.
I can confirm that this works. So only the TIMEOUT settings seem to be ignored.

**Comment by ryonakano** [comment]
Fixed in https://github.com/elementary/os-patches/pull/298. We have no timeout (again) since OS 8
